### ISSUE TITLE
回复显示未登录实际上已经登录

### ISSUE THREAD

**Issue by hsy-design** [guozhigq/flutter_v2ex#30]
![Screenshot_20230306-134258_vvex](https://user-images.githubusercontent.com/52811347/223028445-5e63af5f-0cb5-4e01-b6d1-8595b3df7e20.png)
Aosp 13
重复登录后一直显示如图，其他都挺好，特别是看帖子，感觉非常棒，感谢您

**Comment by hsy-design** [comment]
更新到1.1.1版本已解决，APP内版本号已更新，但APP外应用详情好像没有版本号更新，这么好的应用不上谷歌play或OTA的话就太可惜了，再次感谢，更新好快

**Comment by guozhigq** [comment]
感谢使用😊 也感谢反馈
 
1. 「APP外应用详情好像没有版本号更新」这个我再修复一下
2. OTA的话近期研究一下
3. 等迭代几版稳定了，再上架了谷歌play吧
