### ISSUE TITLE
自由复制增强

### ISSUE THREAD

**Issue by hsy-design** [guozhigq/flutter_v2ex#35]
打开帖子，
帖子内容可以复制，但帖子标题不可。
帖子回复内容长按没有配置事件触发，我看您功能已经实现了，可以默认为自由复制，也可以为如图的“more menu”.
![Screenshot_20230307-221133_vvex.png](https://user-images.githubusercontent.com/52811347/223447066-11a00d4b-b46c-44c4-920e-fbdc77b603e8.png)

**Comment by guozhigq** [comment]
- 😊 帖子标题的复制功能之后会补充上的
- 回复内容区域**长按自由复制**是可以实现的，不过这块准备做**回复多人**，就暂时没弄

**Comment by hsy-design** [comment]
您这回复太效率了，有点好奇回复多人是怎样一个逻辑？我看您回复单人就做的很好，@用户 + #楼层 + 回复内容

难道是长按触发多人回复
@用户A + @用户B ... + #楼层 + 回复内容

@用户A + @用户B ...（users list） 从楼层层主和内容@的用户获取

这个场景可以，但如果这样的话我个人觉得大部分人可能不清楚，因为在安卓领域，习惯长按自由复制或呼出更多菜单。

如果还是原来那样，单点即为回复（无论单人多人）
在回复编辑框直接加入 #楼层 + @用户A + @用户B + 回复内容，用户自己增删艾特内容，会不会更好些，当然#楼层隐藏在编辑框外会更简洁。

当然，这只是我自己的想法，可能有些欠考虑。

**Comment by guozhigq** [comment]
目前回复多人实现方案是：长按每个楼层会变成选中状态，点开回复，会展示所有待回复的用户
确实长按不太符合直观，而且操作起来也不够便捷。
***
1. 之后的回复逻辑会调整为：
- 点击右下角回复主楼 （不变）
- 点击评论回复当前楼 （不变）
- 在输入框内输入@唤起用户列表，支持多选
  - @用户名 #楼层 回复内容
  - @用户名 #楼层 @用户名2 #楼层  回复内容
  
2. 长按评论自由复制功能也会加上

**Comment by guozhigq** [comment]
> 您这回复太效率了，有点好奇回复多人是怎样一个逻辑？我看您回复单人就做的很好，@用户 + #楼层 + 回复内容
> 
> 难道是长按触发多人回复 @用户A + @用户B ... + #楼层 + 回复内容
> 
> @用户A + @用户B ...（users list） 从楼层层主和内容@的用户获取
> 
> 这个场景可以，但如果这样的话我个人觉得大部分人可能不清楚，因为在安卓领域，习惯长按自由复制或呼出更多菜单。
> 
> 如果还是原来那样，单点即为回复（无论单人多人） 在回复编辑框直接加入 #楼层 + @用户A + @用户B + 回复内容，用户自己增删艾特内容，会不会更好些，当然#楼层隐藏在编辑框外会更简洁。
> 
> 当然，这只是我自己的想法，可能有些欠考虑。

最新版 v1.1.22 已调整长按为自由复制，调整@单人、@多人回复逻辑，👏 欢迎继续反馈

**Comment by hsy-design** [comment]
好像引入了新的bug，艾特列表很赞，但单点评论回复好像失效了，看动画像捕捉到了点击事件但没有触发对应函数，长按正常

**Comment by guozhigq** [comment]
> 好像引入了新的bug，艾特列表很赞，但单点评论回复好像失效了，看动画像捕捉到了点击事件但没有触发对应函数，长按正常

>调整：回复区域长按逻辑改为自由复制（导致唤起评论的点击区域为正文外）

目前SelectionArea组件跟其他组件的onTap事件有冲突，导致SelectionArea区域onTap事件被屏蔽，官方正在解决
```dart
InkWell(
  onTap: replyComment,
  child: SelectionArea( ... ),
),
```
我看看有没有其他折中的方案吧

**Comment by guozhigq** [comment]
而且评论内容为纯图片的话，在点击图片时，是查看图片还是唤起评论，这也是个问题

**Comment by hsy-design** [comment]
可以先用三个点的more menu，添加 回复本层 选项，先恢复基本使用

**Comment by hsy-design** [comment]
> 而且评论内容为纯图片的话，在点击图片时，是查看图片还是唤起评论，这也是个问题

点击图片时，查看图片
点击图片外，回复本层

**Comment by hsy-design** [comment]
图片不要显示满屏，比如60% 这样有空白地方可以点击

**Comment by guozhigq** [comment]
> 可以先用三个点的more menu，添加 回复本层 选项，先恢复基本使用

放more menu里 是不是有点繁琐，直接放面板上比较好吧

**Comment by hsy-design** [comment]
折中办法，我把这个当生产级应用😂

**Comment by hsy-design** [comment]
解决有没有，再解决好不好用

**Comment by hsy-design** [comment]
我理解你的意思了，是想在楼层加个回复按钮，这样也挺好

**Comment by guozhigq** [comment]
> 折中办法，我把这个当生产级应用😂

受宠若惊了 🤪，样式设计是个问题
