### ISSUE TITLE
个人用户页面与消息提醒页面 跳转增强

### ISSUE THREAD

**Issue by hsy-design** [guozhigq/flutter_v2ex#36]
如图所示这两个地方直接跳转到帖子主页，如果跳转到帖子指定楼层体验会好很多![Screenshot_20230307-225820_vvex_1.png](https://user-images.githubusercontent.com/52811347/223461111-519aec22-43b4-42ac-bd01-410412911a84.png)![Screenshot_20230307-225829_vvex_1.png](https://user-images.githubusercontent.com/52811347/223461133-a6f365b2-be05-4936-8ebd-fd8d13a05279.png)

**Comment by guozhigq** [comment]
好的🉑️   安排，这里的动作比较大，需要等等

**Comment by guozhigq** [comment]
✅ 消息提醒跳转到指定楼层已实现
❌ 个人主页 - 最近回复因为数据原因暂时无法实现跳转
