### ISSUE TITLE
回复编辑器 增强

### ISSUE THREAD

**Issue by hsy-design** [guozhigq/flutter_v2ex#37]
编辑长文本时，输入法会挡住文本内容。

AOSP 13
百度输入法

**Comment by hsy-design** [comment]
感觉这个问题可能不大，布局画布动态调整一下，就能解决。（😄用嘴编程）

这个客户端使用体验很好，特别是浏览帖子。

因为重度使用所有提的issue会多一些，会有一些自己的想法与建议。时间久了，希望您不会感到厌烦，开源项目全靠开发者个人用爱发电，issue太多怕产生超限效应对您积极性有影响，但每一个issue都是源自喜欢。

再次感谢

**Comment by guozhigq** [comment]
> 编辑长文本时，输入法会挡住文本内容。

忘了考虑文本内容过长的情况了 😂。
没错的，键盘弹出/收起时动态调整输入框高度可解。
没事，你看我给自己也提了那么多需求 哈哈

**Comment by guozhigq** [comment]
> 编辑长文本时，输入法会挡住文本内容。
> 
> AOSP 13 百度输入法

最新版 v1.1.22 已修复回复时文本输入框高度自适应问题，👏 欢迎继续反馈
