### ISSUE TITLE
大佬，在发布版本的时候可以打包一个ipa版吗，方便自签用户使用，谢谢

### ISSUE THREAD

**Issue by amiglistimo** [guozhigq/flutter_v2ex#38]
如题

**Comment by guozhigq** [comment]
感谢关注 🙏
晚些时候看看，这个好像必须要有IOS开发者账号吧

**Comment by dd9913762113** [comment]
我这边有账号，但是获取数据不行

**Comment by guozhigq** [comment]
> 我这边有账号，但是获取数据不行
> 
> ```
> flutter: dynamic_color: Dynamic color not detected on this device.
> flutter: *** Request ***
> flutter: uri: https://www.v2ex.com/recent?p=1
> flutter: method: GET
> flutter: responseType: ResponseType.json
> flutter: followRedirects: true
> flutter: connectTimeout: 12000
> flutter: sendTimeout: 0
> flutter: receiveTimeout: 12000
> flutter: receiveDataWhenStatusError: true
> flutter: extra: {}
> flutter: headers:
> flutter:  user-agent: Mozilla/5.0 (MaciMozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> flutter:
> flutter: dynamic取色失败，采用品牌色
> flutter: scale: 1.0
> flutter: _textTheme: TextTheme#02a9f(displayLarge: TextStyle(debugLabel: (englishLike displayLarge 2021).merge(((blackCupertino displayLarge).apply).apply), inherit: false, color: Color(0xff191c1b), family: NotoSansSC, size: 57.0, weight: 400, letterSpacing: -0.3, baseline: alphabetic, height: 1.1x, leadingDistribution: even, decoration: Color(0xff191c1b) TextDecoration.none), displayMedium: TextStyle(debugLabel: (englishLike displayMedium 2021).merge(((blackCupertino displayMedium).apply).apply), inherit: false, color: Color(0xff191c1b), family: NotoSansSC, size: 45.0, weight: 400, letterSpacing: 0.0, baseline: alphabetic, height: 1.2x, leadingDistribution: even, decoration: Color(0xff191c1b) TextDecoration.none), displaySmall: TextStyle(debugLabel: (englishLike displaySmall 2021).merge(((blackCupertino displaySmall).apply).apply), inherit: false, color: Color(0xff191c1b), family: NotoSansSC, size: 36.0, weight: 400, letterSpacing: 0.0, baseline: alphabetic, height: 1.2x, leadingDistribution: <…>
> flutter: *** DioError ***:
> flutter: uri: https://www.v2ex.com/recent?p=1
> flutter: DioError [DioErrorType.other]: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = 61636
> flutter:
> flutter: get error---------DioError [DioErrorType.other]: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = 61636
> Source stack:
> #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
> #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
> #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
> #3      Request.get (package:flutter_v2ex/http/init.dart:126:28)
> #4      DioRequestWeb.getTopicsRecent (package:flutter_v2ex/http/dio_web.dart:146:34)
> #5      DioRequestWeb.getTopicsByTabKey (package:flutter_v2ex/http/dio_web.dart:74:22)
> #6      _TabBarListState.getTopics (package:flutter_v2ex/components/home/tabbar_list.dart:91:31)
> #7      _TabBarListState.initState (package:flutter_v2ex/components/home/tabbar_list.dart:42:5)
> ```

刚刚看到，不好意思，目前可以了嘛

**Comment by guozhigq** [comment]
v1.1.26添加ipa文件了，第一次打包可能有问题，欢迎继续 issues 😊

**Comment by amiglistimo** [comment]
> v1.1.26添加ipa文件了，第一次打包可能有问题，欢迎继续 issues 😊

大佬，安装了最新的iOS v1.1.27版本，打开显示“网络请求失败 网络异常，请稍后重试”
TrollStore自签安装的，网络确定正常的

**Comment by guozhigq** [comment]
> 

1.1.26网络有问题吗，
27版本有其他问题，我撤回了

**Comment by amiglistimo** [comment]
> > 
> 
> 1.1.26网络有问题吗， 27版本有其他问题，我撤回了

每次在刚进入APP的时候会显示”服务器异常，请稍后重试！”但是可以正常使用，貌似不影响什么

**Comment by amiglistimo** [comment]
> > > > 
> > > 
> > > 
> > > 1.1.26网络有问题吗， 27版本有其他问题，我撤回了
> > 
> > 
> > 每次在刚进入APP的时候会显示”服务器异常，请稍后重试！”但是可以正常使用，貌似不影响什么
> 
> 方便用tg联系不，帮我测一下 ios 🤪

当然可以，如何在tg上找到你，给个群组链接？

**Comment by guozhigq** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 1.1.26网络有问题吗， 27版本有其他问题，我撤回了
> > > 
> > > 
> > > 每次在刚进入APP的时候会显示”服务器异常，请稍后重试！”但是可以正常使用，貌似不影响什么
> > 
> > 方便用tg联系不，帮我测一下 ios 🤪
> 
> 当然可以，如何在tg上找到你，给个群组链接？

https://t.me/+lm_oOVmF0RJiODk1
