### ISSUE TITLE
ios下载地址

### ISSUE THREAD

**Issue by electroNic5moke** [guozhigq/flutter_v2ex#39]
你好，v2ex上别人推荐来的，请问ios怎么下载

**Comment by guozhigq** [comment]
> 你好，v2ex上别人推荐来的，请问ios怎么下载

感谢支持 🙏
因为目前还没有弄到apple开发者账号，所以还没有ipa安装包。在尽快安排了😂

**Comment by guozhigq** [comment]
更新了，大佬 v1.1.26  ipa文件需要自签

**Comment by electroNic5moke** [comment]
谢谢，马上体验一下
