### ISSUE TITLE
最近浏览点击没有无反应

### ISSUE THREAD

**Issue by hsuromky** [guozhigq/flutter_v2ex#40]
![Screenshot_2023-03-08-20-07-18-088_com example flutter_v2ex](https://user-images.githubusercontent.com/117238021/223709651-87c107d3-ee67-4469-a5be-42f6166e60fe.jpg)

**Comment by guozhigq** [comment]
#4 😅尴尬了 哈哈，还没开发「最近浏览」

**Comment by guozhigq** [comment]
> #4 😅尴尬了 哈哈，还没开发「最近浏览」

最新版 v1.1.22 已增加「最近浏览」页面，👏 欢迎继续反馈

**Comment by hsuromky** [comment]
界面ui真不错,而且动画很丝滑,什么时候能上线图片发帖和图片评论呀

**Comment by guozhigq** [comment]
> 界面ui真不错,而且动画很丝滑,什么时候能上线图片发帖和图片评论呀

刚刚看到，什么时候不好说。肯定会有的，应该是先支持带图评论
