### ISSUE TITLE
待优化：唤起@用户列表时，只展示当前楼及之前楼用户

### ISSUE THREAD

**Issue by guozhigq** [guozhigq/flutter_v2ex#44]

**Comment by hsy-design** [comment]
1. 增加艾特全体成员功能，艾特后列表上方加个全选按钮
2. 列表没有去重

**Comment by guozhigq** [comment]
> 1. 增加艾特全体成员功能，艾特后列表上方加个全选按钮
> 2. 列表没有去重

- 全选在安排了。回复全体时，楼层号不是那么必要了，所以需要去重
- 列表去重没必要吧，如果想回复是指定楼层，会跟 **#楼层** 冲突（一个用户可能发布多条评论）

**Comment by hsy-design** [comment]
稳住，预计有一大波需求正在赶来😂
