### ISSUE TITLE
平滑滚动动画时间太长

### ISSUE THREAD

**Issue by hjgyuhuk** [guozhigq/flutter_v2ex#47]
动画时长过长，和其他原生app差异很大，而且列表必须要等动画结束或手动暂停才能点击帖子

**Comment by guozhigq** [comment]
> 动画时长过长，和其他原生app差异很大，而且列表必须要等动画结束或手动暂停才能点击帖子

列表页面吗？详情页有没有这个问题
应该是设置了类ios动画导致的，争取下一版本做成可配置的 😊

**Comment by guozhigq** [comment]
首页的列表动画已经进行了更改，见 [v1.2.1](https://github.com/guozhigq/flutter_v2ex/releases/tag/v1.2.1) 版本。详情页及其他页面的动画跟分页请求有关，暂时不修改了
