### ISSUE TITLE
主题里面的链接无法点击

### ISSUE THREAD

**Issue by hsuromky** [guozhigq/flutter_v2ex#49]
![Screenshot_2023-03-09-19-39-01-761_com example flutter_v2ex](https://user-images.githubusercontent.com/117238021/224014676-aff57a70-b09a-4b42-b150-36e187dd1c59.jpg)
包括问题反馈什么的都不行

**Comment by guozhigq** [comment]
是MIUI吗

原因可能如下：
- 未安装chrome浏览器/未设置为默认浏览器
- 安装的浏览器不支持自定义选项卡

解决办法🤝：请先尝试在「设置」中使用外部浏览器打开

**Comment by guozhigq** [comment]
测试了其他的客户端，在禁用chrome浏览器后，使用默认浏览器打开外部链接。
***
之后的逻辑会借鉴其他app

**Comment by hsuromky** [comment]
是miui
关闭”使用应用内浏览器“就好了 
可以跳转到外部浏览器打开
奈斯

**Comment by guozhigq** [comment]
> 测试了其他的客户端，在禁用chrome浏览器后，使用默认浏览器打开外部链接。
> 
> 之后的逻辑会借鉴其他app

已更新，见最新版 v1.1.25
