### ISSUE TITLE
https://www.v2ex.com/recent 这个页面并不是最近浏览的页面

### ISSUE THREAD

**Issue by mzbb** [guozhigq/flutter_v2ex#53]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/19501430/224229296-a9b839fe-92ac-4f49-a273-0ed3aea4d601.png">
这个才是，看了下代码你好像弄错了？

**Comment by guozhigq** [comment]
啊 确实，取错dom了。
抱歉，下一版本修改

**Comment by mzbb** [comment]
我看其他的客户端好像都是做的本地缓存，获取这个dom需要请求桌面端首页，还限制了最多5条数据，而且失效时间很短（貌似只有几分钟），建议也做成本地缓存

**Comment by guozhigq** [comment]
> 我看其他的客户端好像都是做的本地缓存，获取这个dom需要请求桌面端首页，还限制了最多5条数据，而且失效时间很短（貌似只有几分钟），建议也做成本地缓存

嗯 有道理👍。会加上的

**Comment by guozhigq** [comment]
v1.1.27已增加本地缓存
