### ISSUE TITLE
密码框问题

### ISSUE THREAD

**Issue by lqxhub** [guozhigq/flutter_v2ex#59]
复现流程
1. 把密码输入框设置为密码可见后,登录错误(如输错密码)
2. 再次输入密码时,密码框显示的是不显示密码,但是在输入的时候,是显示密码的

**Comment by guozhigq** [comment]
> 复现流程
> 
> 1. 把密码输入框设置为密码可见后,登录错误(如输错密码)
> 2. 再次输入密码时,密码框显示的是不显示密码,但是在输入的时候,是显示密码的

没有复现😂
 输入密码，显示密码，点击登录出现错误页面刷新后，状态还是显示密码，但是输入的密码是****

**Comment by lqxhub** [comment]
额额额 可能是我对那个 可见和不可见的图标理解反了🤣🤣🤣  那我关了 这个issue吧

**Comment by guozhigq** [comment]
😂 那个确实，我第一用也有点晕。登录功能没问题就行 🐶
