### ISSUE TITLE
［添加高级功能］关键词屏蔽 发帖人屏蔽

### ISSUE THREAD

**Issue by hsy-design** [guozhigq/flutter_v2ex#63]
建议添加捐赠解锁高级功能
关键词屏蔽 发帖人屏蔽

可持续的开源之道才是最优解

**Comment by guozhigq** [comment]
发帖人屏蔽不就是block么 🐶
关键词屏蔽 可以实现，不过爬的网页只有标题，所以没法对内容做过滤
如果捐赠的话，更多是自愿吧 🤪，这两功能不是那么够硬

**Comment by hsy-design** [comment]
不够硬就慢慢来嘛 前期高级功能少就收个几块钱。 后期功能多，可以涨价。对于早期捐赠用户加量不加价。就要标题block和user block，功能虽然不够硬核，但是比较实用，目前没看到谁实现的比较好，基本上只有浏览器的油猴脚本。v2不只IT行业还有更多创意者，花点小钱让自己更舒服，相信不少人还是喜欢的。

**Comment by hsy-design** [comment]
高级版解锁码解锁所有功能
比如
23.03.16 屏蔽功能 当前价格1元
23.03.20 帖子离线缓存功能 变为2元
...
早捐早享受早优惠，就赚非it领域人员认知范围以外的钱，代码相关藏都不用藏，保存好自己的签名跟密钥就行。

也不指望赚多少钱，就指望更新代码的时候有杯咖啡喝

**Comment by guozhigq** [comment]
> 

可以的，哈哈。很有想法💡。需要好好想一想

**Comment by guozhigq** [comment]
来tg https://t.me/+lm_oOVmF0RJiODk1
