### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by sheey11** [guozhigq/flutter_v2ex#68]
网页能打开，v2er 也能打开，但是 vvex 是网络错误，代理开的是全局
![](https://user-images.githubusercontent.com/13375959/226575998-b72ceed2-7a7e-45ee-a968-c3bfb398b33e.jpg)

**Comment by guozhigq** [comment]
其他节点也异常吗

**Comment by guozhigq** [comment]
> 其他节点也异常吗

登录之前请求正常吗

**Comment by sheey11** [comment]
前几天第一次安装之后就是这样的情况，刷新了几次突然好了，才登陆回去的。今天打开多刷几次还是不行，感觉应该是个bug了

另外设备是root了的，我可以尽可能提供信息

**Comment by guozhigq** [comment]
> 前几天第一次安装之后就是这样的情况，刷新了几次突然好了，才登陆上去的。今天打开多刷几次还是不行，感觉应该是个bug了
> 
> 节点方面基本都测试了一遍(港台/日本/新加坡/美 和其他一些小国)，都是加载失败
> 
> 另外设备是root了的，我可以尽可能提供信息

来群组讨论吧🤝  方便～   https://t.me/+lm_oOVmF0RJiODk1
