### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by bilibili2233a** [guozhigq/flutter_v2ex#75]
在浏览器是可以打开网页的，app就一直提示没网络
![Screenshot_20230406_012021_com.guozhigq.vvex.jpg](https://user-images.githubusercontent.com/99982054/230156303-047e52e1-efa8-4d8d-8b01-0e52f3671c7b.jpg)

![Screenshot_20230406_012026_com.guozhigq.vvex.jpg](https://user-images.githubusercontent.com/99982054/230156305-d71ddee1-ffc1-49fe-a0df-22a792c05645.jpg)

![Screenshot_20230406_012039_com.kiwibrowser.browser.dev.jpg](https://user-images.githubusercontent.com/99982054/230156304-59406ff0-5885-45c3-811e-7e722cb1dcba.jpg)

**Comment by bilibili2233a** [comment]
解决了，加密dns关了就正常
![Screenshot_20230406_012703_com.guozhigq.vvex.jpg](https://user-images.githubusercontent.com/99982054/230157578-d3db8f32-c1f6-4afd-ac18-a2a99d30b07a.jpg)

**Comment by guozhigq** [comment]
好的 👍
