### ISSUE TITLE
接口无法访问，返回socketexception: connection reset by peer

### ISSUE THREAD

**Issue by yangblink** [guozhigq/flutter_v2ex#90]
我的问题跟 #75 差不多，用的ios的 simulator，应该如何设置，模拟器用了机器的梯子，可以正常访问youtube。

<img width="452" alt="image" src="https://github.com/guozhigq/flutter_v2ex/assets/2688285/2630d419-ffa6-49db-a1f2-b8119deee322">

**Comment by guozhigq** [comment]
模拟器里可以正常访问v2吗

**Comment by yangblink** [comment]
可以的
<img width="452" alt="image" src="https://github.com/guozhigq/flutter_v2ex/assets/2688285/6ec2bb9a-d13c-4b01-8b51-c8723b00fc4c">

**Comment by guozhigq** [comment]
在lib/http/init.dart 文件中88行左右，手动修改一下代理试试呢

**Comment by yangblink** [comment]
> 在lib/http/init.dart 文件中88行左右，手动修改一下代理试试呢

可以了，👍！
